project:
  type: website
  
execute:
  freeze: false

website:
  title: "Lewis A. Jones"
  site-url: https://lewisajones.com
  description: "Personal website"
  image: "gallery/Arolla.jpg"
  favicon: "icons/favicon.png"
  search: false
  open-graph: 
    image: "gallery/Arolla.jpg"
    image-width: 500
    image-height: 500
    locale: en-GB
  twitter-card: 
    title: Lewis A. Jones
    description: The personal website of Lewis A. Jones
    image: "gallery/Arolla.jpg"
    image-width: 500
    image-height: 500
    card-style: summary
    creator: "@LewisAlanJones"
    site: "@LewisAlanJones"
  navbar:
    title: false
    logo: images/logo.png
    background: "#F6F5F3"
    logo-alt: "Dr Lewis A. Jones"
    foreground: "#00bc8c"
    left:
      - text: "About"
        file: about.qmd
      - text: "Experience"
        file: experience.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "R Packages"
        file: packages.qmd
      - text: "Gallery"
        file: gallery.qmd
    right:    
      - icon: twitter
        href: "https://twitter.com/LewisAlanJones"
      - icon: github
        href: "https://github.com/LewisAJones"
      - icon: envelope-fill
        href: "mailto:LewisA.Jones@outlook.com"
      - icon: mortarboard-fill
        href: "https://scholar.google.com/citations?user=X0AvsOkAAAAJ&hl"

format:
  html:
    theme:
      light: themes/light.scss
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true

editor: source

