project:
  type: website
  
execute:
  freeze: false

website:
  title: "Lewis A. Jones"
  site-url: https://lewisajones.com
  description: "Personal website"
  image: "gallery/Arolla.jpg"
  favicon: "icons/coral.png"
  search: false
  open-graph: 
    image: "gallery/Arolla.jpg"
    image-width: 500
    image-height: 500
    locale: en-GB
  twitter-card: 
    title: Lewis A. Jones
    description: The personal website of Lewis A. Jones
    image: "gallery/Arolla.jpg"
    image-width: 500
    image-height: 500
    card-style: summary
    creator: "@LewisAlanJones"
    site: "@LewisAlanJones"
  navbar:
    pinned: true
    title: "Lewis A. Jones"
    logo-alt: "Dr Lewis A. Jones"
    background: transparent
    right:    
      - text: "About"
        file: index.qmd
      - text: "Research"
        file: research.qmd
      - text: "Experience"
        file: experience.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Software"
        menu:
          - text: "palaeoverse"
            icon: "gear-fill"
            href: packages.qmd#palaeoverse
          - text: "rphylopic"
            icon: "bug-fill"
            href: packages.qmd#rphylopic
          - text: "rmacrostrat"
            icon: "hammer"
            href: packages.qmd#rmacrostrat
          - text: "sepkoski"
            icon: "graph-up"
            href: packages.qmd#sepkoski
      - text: "Gallery"
        file: gallery.qmd
      - icon: twitter
        href: "https://twitter.com/LewisAlanJones"
      - icon: github
        href: "https://github.com/LewisAJones"
      - icon: envelope-fill
        href: "mailto:Lewis.Jones@ucl.ac.uk"
      - icon: mortarboard-fill
        href: "https://scholar.google.com/citations?user=X0AvsOkAAAAJ&hl"
  page-footer: 
    background: "#f6f5f3"
    left: |
      © Copyright 2024 Lewis A. Jones
    center: |
      [![](/images/logo-palaeoverse.png){fig-alt="Palaeoverse" width=25px}](https://palaeoverse.org)
    right: 
      - icon: twitter
        href: "https://twitter.com/LewisAlanJones"
      - icon: github
        href: "https://github.com/LewisAJones"
      - icon: envelope-fill
        href: "mailto:Lewis.Jones@ucl.ac.uk"
      - icon: mortarboard-fill
        href: "https://scholar.google.com/citations?user=X0AvsOkAAAAJ&hl"
format:
  html:
    theme:
      light: themes/light.scss
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true

editor: source

